### ISSUE TITLE
html loads empty

### ISSUE THREAD

**Issue by FJLopezGarcia** [angular/protractor-timeline-plugin#5]
Hi all, 
When i run Protractor with the plugin in place the output files are created but the html doesnt load results,
Do you know the reason?
<img width="1408" alt="screen shot 2016-02-14 at 21 02 00" src="https://cloud.githubusercontent.com/assets/6631983/13036093/97319fe2-d35e-11e5-904f-696dd6c93eb6.png">

HTML loads empty (i have tried with Chrome, Safari, etc...)
JSON contains data:

[{"source":"Test Process","id":0,"command":{"name_":"getAvailableLogTypes","parameters_":{}},"start":1455414657512,"end":1455414657521},{"source":"Test Process","id":1,"command":{"name_":"maximizeWindow","parameters_":{}},"start":1455414657632,"end":1455414657938},{"source":"Test Process","id":2,"command":{"name_":"get","parameters_":{"url":"http://localhost:8100/"}},"start":1455414657940,"end":1455414658589},{"source":"Test Process","id":3,"command":{"name_":"switchToFrame","parameters_":{"id":null}},"start":1455414661598,"end":1455414661607},{"source":"Test Process","id":4,"command":{"name_":"executeScript","parameters_":{"script":"(function () {if (typeof axe === \"object\" && axe.version) { return; }var s = document.createElement(\"script\");s.innerHTML = \"/_! aXe v1.1.1\n \* Copyright (c) 2015 Deque Systems, Inc.\n *\n \* Your use of this Source Code Form is subject to the terms of the Mozilla Public\n \* License, v. 2.0. If a copy of the MPL was not distributed with this\n \* file, You can obtain one at http://mozilla.org/MPL/2.0/.\\n *\n \* This entire copyright notice must appear in every copy of this file you\n \* distribute or in any file that contains substantial portions of this source\n \* code.\n */\n(function (window, document) {\n\n/_exported clone _/\n\n/__\n \* Deeply clones an object or array\n \* @param  {Mixed} obj The object/array to clone\n \* @return {Mixed}     A clone of the initial object or array\n */\nfunction clone(obj) {\n\t'use strict';\n\tvar index, length,\n\t\tout = obj;\n\n\tif (obj !== null && typeof obj === 'object') {\n\t\tif (Array.isArray(obj)) {\n\t\t\tout = [];\n\t\t\tfor (index = 0, length = obj.length; index < length; index++) {\n\t\t\t\tout[index] = clone(obj[index]);\n\t\t\t}\n\t\t} else {\n\t\t\tout = {};\n\t\t\t// jshint forin: false\n\t\t\tfor (index in obj) {\n\t\t\t\tout[index] = clone(obj[index]);\n\t\t\t}\n\t\t}\n\t}\n\treturn out;\n}\n/_exported matchesSelector _/\n/_*\n \* Polyfill for Element#matches\n \* @param {HTMLElement} node The element to test\n \* @param {String} selector The selector to test element against\n \* @return {Boolean}\n */\nvar matchesSelector = (function () {\n\t'use strict';\n\n\tvar method;\n\n\tfunction getMethod(win) {\n\n\t\tvar index, candidate,\n\t\t\telProto = win.Element.prototype,\n\t\t\tcandidates = ['matches', 'matchesSelector', 'mozMatchesSelector', 'webkitMatchesSelector', 'msMatchesSelector'],\n\t\t\tlength = candidates.length;\n\n\t\tfor (index = 0; index < length; index++) {\n\t\t\tcandidate =.........

**Comment by FJLopezGarcia** [comment]
fixed you need to serve the file from server. i have used webserver
//https://www.npmjs.com/package/gulp-webserver

regards
Javi

**Comment by LaiaPR** [comment]
Hi! 

I can load the results but are ... empty? 

![selection_096](https://cloud.githubusercontent.com/assets/13735417/19777095/ff759770-9c76-11e6-9547-94c2b5c6c730.png)

The Json file contains data... so, I don't know what I have to do. 

Have it worked for you? Any tip?

Thanks!

**Comment by sjelin** [comment]
The reason is that it's a cross origin request, which is a security issue.  It really shouldn't be a cross origin request, so your server must be set up in a weird way.
